[config]
default_to_workspace = false

[tasks.solana]
command = "solana-install"
args = ["init", "1.18.8"]

[tasks.avm]
command = "avm"
args = ["use", "0.29.0"]

[tasks.setup]
dependencies = ["avm", "solana"]