[toolchain]
# Check https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu.html
# for valid toolchains.
#channel = "stable-x86_64-apple-darwin"
channel = "1.75.0"
component = ["cargo-sort", "clippy"]